image: google/cloud-sdk:alpine

stages:
  - deploy

deploy:
  stage: deploy
  environment: Production
  only:
    - master
  script:
    - echo $SERVICE_ACCOUNT > /tmp/$CI_PIPELINE_ID.json
    - gcloud auth activate-service-account --key-file /tmp/$CI_PIPELINE_ID.json
    - gcloud --quiet --project $PROJECT_ID app deploy --appyaml=deploy/app.yaml

after_script:
  - rm /tmp/$CI_PIPELINE_ID.json